version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
